# Generated by Django 6.0.2 on 2026-03-08 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('craftsman', 'Craftsman'), ('farmer', 'Farmer'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('builder', 'Builder'), ('gardener', 'Gardener'), ('other', 'Other Service')], max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='heroes/photos/')),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_ro', models.TextField(blank=True, verbose_name='Description (RO)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (RU)')),
                ('services', models.TextField(blank=True, help_text='Services offered — comma-separated or free text')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = displayed first')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if not applicable', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
